m

diff --git a/.github/workflows/play_move.yml b/.github/workflows/play_move.yml
--- a/.github/workflows/play_move.yml
+++ b/.github/workflows/play_move.yml
@@ -18,9 +18,9 @@ jobs:
         
     - name: Build project
       run: |
-        test -f bin/build.sh || (echo "File build.sh not found" && exit 1)
-        chmod +x bin/build.sh
-        bin/build.sh || echo "Compilation error"
+        test -f build.sh || (echo "File build.sh not found" && exit 1)
+        chmod +x build.sh
+        build.sh || echo "Compilation error"
         
     - name: Verify binary exists
       run: test -f baeagn || (echo "Binary not found" && exit 1)
